<?php
    require "../procedimientos/procedimientos.php";
    $conexion = new conexion();
    $conectar= new mysqli ($conexion->getServer(),$conexion->getUser(),$conexion->getPass(),$conexion->getDb());
    echo '<div>';
        echo '<h3>Añadir incidencia</h3>';
        echo '<form method="post" class="form-horizontal" action="../consultas/conAddIncidencia.php">';
        echo '<div>';
        echo '<label>Alumno</label>';
        echo '<select name="nia" class="form-control" id="sel1" required="required">';
        require "../consultas/addIncidencia/listadoAlumno.php";
        echo '</select>';
        echo '</div>';
        echo '<div>';
        echo '<label>Tipo de incidencia</label>';
        echo '<select name="tipo_inc" class="form-control" id="sel1" required="required">';
        require "../consultas/addIncidencia/listadoTipoInc.php";
        echo '</select>';
        echo '</div>';
        echo '<div>';
        echo '<label>Asignatura</label>';
        echo '<input type="text" name="asignatura" class="form-control" required="required"/>';
        echo '</div>';
        echo '<div>';
        echo '<label>Hora</label>';
        echo '<select name="hora" class="form-control" id="sel1" required="required">';
        require "../consultas/addIncidencia/listadoHoras.php";
        echo '</select>';
        echo '</div>';
        echo '<div>';
        echo '<label>Fecha de la incidencia</label>';
        echo '<input type="date" name="fecha_incidencia" required="required" value="'.date("Y-m-d").'"/>';
        echo '</div>';
        echo '<div>';
        echo '<label>Descripción de la incidencia</label>';
        echo '<input type="text" name="descripcion" required="required" />';
        echo '</div>';
        echo '<div>';
        echo '<input type="submit" value="Enviar incidencia"/>';
        echo '</div>';
        echo '</form>';
    echo '</div>';
?>
